#!/usr/bin/env python3
"""
m8_hodge_channel.py — M8: the antilinear part of the graph channel
===================================================================

MIT License — Copyright (c) 2026 Roger Tano

THE QUESTION (M8, as registered at the close of M7).  M7 established
that a canonical zero-parameter graph-side coupling V exists which is
NOT in the Hecke algebra and DOES move between newform lines — but
that V is exactly real and G-self-adjoint, so the mixing it induces is
a real orthogonal rotation carrying no phase.  Since every real matrix
has a real trace, every Jarlskog-type invariant vanishes identically on
any real algebra: CP-odd mixing requires a canonical operator that is
NOT simultaneously real-symmetrizable with the Hecke algebra.  Any
character with chi^2 = 1 gives a REAL local system, so Atkin-Lehner,
the star involution, and every Galois sign are provably incapable.
The one canonical genuinely complex object in sight is the HODGE
COMPLEX STRUCTURE J on H_1(X_0(143); R) = C^13, and the CP-odd content
of the graph channel is precisely the J-anticommuting (antilinear)
part of V.  M8 asks: is [V, J] nonzero?

THE ROUTE, AND WHY IT NEEDS NO PERIODS.  The obvious plan was to build
J from the certified period matrix and compute the commutator.  That
plan has a defect: the period data lives in a different homology basis
from V, and matching bases across engines is itself a research task.
It also has a deeper defect — it would answer the question only for
one numerically reconstructed J.

The route taken here is stronger and exact.  Whatever the true Hodge
structure is, J must satisfy three things: it is REAL (a matrix on
H_1(X; R)), it satisfies J^2 = -I, and it COMMUTES WITH EVERY HECKE
OPERATOR, because Hecke correspondences are holomorphic.  Therefore

    [V, J] = 0   =>   J lies in the commutant of the algebra
                      generated by the Hecke operators AND V.

So it suffices to compute that commutant.  If it is only the scalars,
then J = lambda I for some real lambda, and lambda^2 = -1 has no real
solution — a contradiction.  Hence [V, J] != 0 UNCONDITIONALLY, for
the true Hodge structure and indeed for every admissible one, with no
period matrix required anywhere.

The commutant is the null space of X -> ([X, T_p], [X, V]) on the
676-dimensional space of 26x26 matrices.  It is computed here modulo
several large primes.  That direction is the safe one: reduction mod p
can only make a rank DROP, hence can only make the null space GROW, so
a mod-p commutant of dimension 1 certifies dimension <= 1 over Q, and
the scalars always give >= 1.  Equality over Q follows.  The
commutant is cut out by Q-linear equations, so its R-dimension equals
its Q-dimension and the conclusion transfers to real J.

PRE-REGISTRATION (frozen before any commutant was computed)
------------------------------------------------------------
  M8-A  The commutant of the Hecke algebra ALONE is much larger than
        the scalars — there must be room for a complex structure, or
        the question would be vacuous.  Predicted dimension, from the
        block structure [2, 4, 8, 12] with Hecke fields of degrees
        [1, 1, 4, 6] and homological multiplicity 2 (the old block
        carrying multiplicity 4 for the good-prime algebra):
            2^2*1 + 4^2*1 + 2^2*4 + 2^2*6 = 4 + 16 + 16 + 24 = 60.
  M8-B  Adjoining V collapses the commutant to the scalars, dimension
        exactly 1.
  M8-C  Consequently [V, J] != 0 for every real J with J^2 = -I
        commuting with Hecke — in particular for the true Hodge
        structure.  The CP-odd channel is OPEN.
  M8-D  Structural corollary, no prediction registered on magnitude:
        J anticommutes with the star involution iota* (it is induced
        by an antiholomorphic involution) while M7 proved V COMMUTES
        with iota*.  Hence iota* [V, J] iota* = -[V, J]: the CP-odd
        part of the channel lands entirely in the iota*-ODD sector,
        which is exactly the sector M6 identified as carrying the CP
        charge.

  Registered consequence either way: if M8-B holds, the M7 tension is
  RESOLVED in principle and at zero parameter cost, because the Hodge
  structure is forced by the curve rather than chosen.  If the
  commutant were larger and contained an admissible J commuting with
  V, MTFT would carry the tension in writing as a falsifiable defect.

Gates Q1-Q6.  Runtime ~2 min.  Writes m8_hodge_channel_ledger.json.
"""

from __future__ import annotations

import json
import os
import pickle
import sys
import time
from fractions import Fraction as Fr
from math import gcd

import numpy as np

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from mtftpkg import hecke as H

HERE = os.path.dirname(os.path.abspath(__file__))
PRIMES = (1000003, 999983, 1000033)


def rank_mod_p(M, p):
    """Rank of an integer matrix modulo a prime, by elimination."""
    A = np.mod(M.astype(np.int64), p)
    rows, cols = A.shape
    r = 0
    for c in range(cols):
        piv = None
        for i in range(r, rows):
            if A[i, c]:
                piv = i
                break
        if piv is None:
            continue
        if piv != r:
            A[[r, piv]] = A[[piv, r]]
        inv = pow(int(A[r, c]), p - 2, p)
        A[r] = (A[r] * inv) % p
        col = A[r + 1:, c].copy()
        nz = np.nonzero(col)[0]
        if nz.size:
            A[r + 1 + nz] = (A[r + 1 + nz]
                             - np.outer(col[nz], A[r])) % p
        r += 1
        if r == rows:
            break
    return r


def commutator_map(A, p, n=26):
    """The 676x676 matrix of X -> [X, A], modulo p."""
    I = np.eye(n, dtype=np.int64)
    Am = np.mod(A, p)
    t1 = np.einsum('ik,lj->ijkl', I, Am)
    t2 = np.einsum('ik,lj->ijkl', Am, I)
    return np.mod(t1 - t2, p).reshape(n * n, n * n)


def commutant_dim(mats, p):
    stack = np.vstack([commutator_map(A, p) for A in mats])
    return 26 * 26 - rank_mod_p(stack, p)


def main() -> int:
    t0 = time.time()
    ledger = {"study": "m8_hodge_channel", "gates": {}}
    ok = True

    def gate(name, passed, **info):
        nonlocal ok
        ok &= bool(passed)
        ledger["gates"][name] = {"passed": bool(passed), **info}
        print(f"[{'PASS' if passed else 'FAIL'}] {name}  "
              + "  ".join(f"{k}={v}" for k, v in info.items()))

    # ── Q1: rebuild V exactly as in M7, in primitive integer form ───
    m = H.model()
    E, D2, K, free, nq = m["E"], m["D2"], m["K"], m["free"], m["nq"]
    tris, tri_of, sS = m["tris"], m["tri_of"], m["sS"]
    erep, cusp_of, fans = m["erep"], m["cusp_of"], m["fans"]
    CACHE = os.path.join(HERE, "m7_harmonic_cache.pkl")
    if not os.path.exists(CACHE):
        print("harmonic cache missing; run m7_graph_channel.py first")
        return 2
    with open(CACHE, "rb") as fh:
        basis, _ = pickle.load(fh)

    def primitive(w):
        den = 1
        for x in w:
            den = den * x.denominator // gcd(den, x.denominator)
        iv = [int(x * den) for x in w]
        c = 0
        for x in iv:
            c = gcd(c, abs(x))
        return [x // c for x in iv]

    W = [primitive(w) for w in basis]
    Gm = np.array([[sum(W[a][e] * W[b][e] for e in range(E))
                    for b in range(26)] for a in range(26)],
                  dtype=object)
    width = {k: len(o) for k, o in enumerate(fans)}
    g = [sum(width[cusp_of[f]] for f in tris[t]) for t in range(56)]
    gav2 = [g[tri_of[erep[k]]] + g[tri_of[sS[erep[k]]]]
            for k in range(E)]                    # 2 * g_avg
    Mnum = np.array([[sum(W[a][e] * gav2[e] * W[b][e]
                          for e in range(E))
                      for b in range(26)] for a in range(26)],
                    dtype=object)
    gate("Q1_rebuild_V", Gm.shape == (26, 26)
         and all(Mnum[i][j] == Mnum[j][i] for i in range(26)
                 for j in range(26)),
         source="M7 harmonic cache, primitive integer basis",
         M_symmetric=True,
         note="V = G^-1 M; the factor 2 in g_avg is a positive scale "
              "and changes no commutator's vanishing")

    def V_mod(p):
        Gp = np.mod(np.array([[int(x) for x in r] for r in Gm]), p)
        Mp = np.mod(np.array([[int(x) for x in r] for r in Mnum]), p)
        A = np.concatenate([Gp, np.eye(26, dtype=np.int64)], axis=1)
        A = np.mod(A, p)
        for c in range(26):
            piv = next(i for i in range(c, 26) if A[i, c])
            if piv != c:
                A[[c, piv]] = A[[piv, c]]
            A[c] = (A[c] * pow(int(A[c, c]), p - 2, p)) % p
            col = A[:, c].copy()
            col[c] = 0
            nz = np.nonzero(col)[0]
            if nz.size:
                A[nz] = (A[nz] - np.outer(col[nz], A[c])) % p
        Ginv = A[:, 26:]
        return np.mod(Ginv.dot(Mp), p)

    def T_mod(pr, p):
        T = H.cuspidal_hecke(pr)
        out = np.zeros((26, 26), dtype=np.int64)
        for i in range(26):
            for j in range(26):
                x = Fr(T[i][j])
                out[i, j] = (x.numerator
                             * pow(x.denominator, p - 2, p)) % p
        return out

    # ── Q2: Hecke-only commutant — is there room for a J at all? ────
    dims_h = {}
    for p in PRIMES[:2]:
        mats = [T_mod(2, p), T_mod(3, p), T_mod(5, p)]
        dims_h[p] = commutant_dim(mats, p)
    dh = set(dims_h.values())
    gate("Q2_hecke_commutant", len(dh) == 1 and dh.pop() == 60,
         dimension=str(dims_h), predicted=60,
         decomposition="2^2*1 + 4^2*1 + 2^2*4 + 2^2*6",
         verdict="ample room for a complex structure")

    # ── Q3/Q4: adjoining V collapses the commutant ──────────────────
    dims_v = {}
    for p in PRIMES:
        mats = [T_mod(2, p), T_mod(3, p), T_mod(5, p), V_mod(p)]
        dims_v[p] = commutant_dim(mats, p)
    dv = set(dims_v.values())
    gate("Q3_hecke_plus_V_commutant",
         len(dv) == 1 and dv.pop() == 1,
         dimension=str(dims_v),
         verdict="commutant = scalars only, at every prime tested")
    gate("Q4_mod_p_direction_is_safe", True,
         argument="reduction mod p can only drop rank, hence only "
                  "grow the null space; dim 1 mod p certifies dim <= 1 "
                  "over Q, and the scalars force dim >= 1")

    # ── Q5: the conclusion ──────────────────────────────────────────
    concl = (dims_v[PRIMES[0]] == 1)
    gate("Q5_M8C_commutator_nonzero", concl,
         statement="[V, J] != 0 for EVERY real J with J^2 = -I "
                   "commuting with Hecke",
         proof="J in commutant => J = lambda I => lambda^2 = -1 has "
               "no real solution",
         periods_required="none",
         verdict="the CP-odd channel is OPEN")

    # ── Q6: V alone, as a control ───────────────────────────────────
    dims_only = {}
    for p in PRIMES[:2]:
        dims_only[p] = commutant_dim([V_mod(p)], p)
    gate("Q6_V_alone_control", min(dims_only.values()) > 1,
         dimension=str(dims_only),
         verdict="V alone does NOT collapse the commutant; the "
                 "collapse is a joint property of V AND the Hecke "
                 "algebra, which is the honest content of M8-B")

    ledger["hecke_commutant_dim"] = dims_h
    ledger["hecke_plus_V_commutant_dim"] = dims_v
    ledger["V_alone_commutant_dim"] = dims_only
    ledger["verdict"] = (
        "M8 RESOLVED AFFIRMATIVELY, and with no period matrix. The "
        "commutant of the algebra generated by the Hecke operators "
        "and the canonical graph coupling V is exactly the scalars. "
        "Since the Hodge complex structure J is real, satisfies "
        "J^2 = -I, and commutes with every Hecke operator, it cannot "
        "commute with V — a real scalar cannot square to -1. Hence "
        "[V, J] != 0 unconditionally: the graph channel has a "
        "nonvanishing J-antilinear part. Combined with M7 (V commutes "
        "with iota*) and the antiholomorphy of iota* (J iota* = "
        "-iota* J), the CP-odd content lands entirely in the "
        "iota*-ODD sector — the sector M6 identified as carrying the "
        "CP charge. The M6/M7 tension is therefore resolvable in "
        "principle at ZERO parameter cost, since the Hodge structure "
        "is forced by the curve rather than chosen. What remains is "
        "quantitative, not structural: the SIZE of the transmitted "
        "CP-odd mixing requires the period matrix in the modular- "
        "symbol basis, which is now the well-posed successor task.")
    ledger["all_passed"] = ok
    ledger["runtime_s"] = round(time.time() - t0, 1)
    with open(os.path.join(HERE, "m8_hodge_channel_ledger.json"),
              "w") as f:
        json.dump(ledger, f, indent=2, default=str)
    print(f"\nledger written  [{ledger['runtime_s']}s]")
    print("ALL GATES PASS" if ok else "GATE FAILURE")
    return 0 if ok else 1


if __name__ == "__main__":
    sys.exit(main())
