"""
hecke_ke_exact — exact-arithmetic break of Hecke-CDH (eprint 2025/1681).

No eigendecomposition, no floating point, no semisimplicity assumption,
no "distinguishing form" hypothesis.  Only commutativity -- the same
property the protocol needs in order to work at all.

  Eve has f, H_A(f), H_B(f) and wants H_A(H_B(f)).

  Let T be the Hecke algebra (a commutative Q-algebra of matrices,
  computable from N and k alone -- entirely public).  Eve solves the
  linear system

        X in T,   X(f) = H_A(f)

  for ANY solution X.  One exists, namely X = H_A, so the system is
  consistent.  Then, purely by commutativity,

        X(H_B f) = H_B(X f) = H_B(H_A f) = H_A(H_B f)

  which is the shared secret.  Eve never learns N_1..N_s, and does not
  need to: the secret operator is only ever used through its action,
  and any algebra element with the same action on f is as good.

Complexity: one nullspace/solve of size d x dim(T).  Both are tiny.
"""
from __future__ import annotations
import sys, os, random
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))

import numpy as np
import sympy as sp
from x0143_particle_box import P1, tessellation, ModularSymbols

N = 143
random.seed(11)


def hecke(ms, p):
    M = ms.hecke_on_quotient(p)
    return sp.Matrix(np.rint(np.array(M, dtype=float)).astype(int).tolist())


def algebra_basis(gens, d):
    """Q-basis of the unital algebra generated by commuting matrices."""
    basis, vecs = [], []
    frontier = [sp.eye(d)]
    seen_rank = 0
    while frontier:
        nxt = []
        for M in frontier:
            v = sp.Matrix([M[i, j] for i in range(d) for j in range(d)]).T
            trial = sp.Matrix.vstack(*(vecs + [v])) if vecs else v
            if trial.rank() > seen_rank:
                seen_rank = trial.rank()
                basis.append(M)
                vecs.append(v)
                for g in gens:
                    nxt.append(M * g)
        frontier = nxt
    return basis


def main():
    p1 = P1(N)
    tessellation(N)
    ms = ModularSymbols(p1)
    d = ms.dim

    S_A = [2, 3, 5, 7]
    S_B = [17, 19, 23, 29]
    T = {p: hecke(ms, p) for p in S_A + S_B}

    # public Hecke algebra -- depends only on (N, k)
    gens = [T[p] for p in S_A + S_B]
    B = algebra_basis(gens, d)
    m = len(B)
    print(f"d = {d},  dim_Q of the Hecke algebra T = {m}")

    # ---- protocol ------------------------------------------------------
    s = 3
    A_ints = [tuple(random.sample(S_A, 3)) for _ in range(s)]
    B_ints = [tuple(random.sample(S_B, 3)) for _ in range(s)]
    HA, HB = sp.eye(d), sp.eye(d)
    for (a, b, c) in A_ints:
        HA = HA * T[a] * T[b] * T[c]
    for (a, b, c) in B_ints:
        HB = HB * T[a] * T[b] * T[c]

    f = sp.Matrix([random.randint(1, 9) for _ in range(d)])
    pub_A, pub_B = HA * f, HB * f
    shared = HA * HB * f

    print(f"Alice N_i = {[a*b*c for a,b,c in A_ints]}")
    print(f"Bob   M_i = {[a*b*c for a,b,c in B_ints]}")

    # ---- Eve: exact rational solve -------------------------------------
    # columns E_k(f); solve  sum_k x_k E_k(f) = pub_A
    Mcols = sp.Matrix.hstack(*[Ek * f for Ek in B])
    sol = Mcols.gauss_jordan_solve(pub_A)[0]
    # gauss_jordan_solve returns (particular + free params); pin frees to 0
    sol = sol.subs({t: 0 for t in sol.free_symbols})
    X = sp.zeros(d, d)
    for k in range(m):
        X += sol[k] * B[k]

    print(f"\nEve found X in T with X(f) = H_A(f):  "
          f"{sp.simplify(X*f - pub_A).is_zero_matrix}")
    print(f"Is X literally H_A?  {sp.simplify(X - HA).is_zero_matrix}  "
          f"(it does not need to be)")

    eve = X * pub_B
    ok = sp.simplify(eve - shared).is_zero_matrix
    print(f"\nEve's X(H_B f) == true shared secret, EXACTLY over Q:  {ok}")
    print(f"shared[0] = {shared[0]}")
    print(f"eve[0]    = {eve[0]}")


if __name__ == "__main__":
    main()
