import numpy as np
from mtft.surface import arithspin as AS

def test_cc27_theta_compatible_lift_is_Q8_and_intertwines():
    Q = AS.theta_compatible_al_lift(); I = np.eye(2)
    assert np.allclose(Q["A2"], -I) and np.allclose(Q["B2"], -I) and np.allclose(Q["AB2"], -I) and np.allclose(Q["commutator"], -I)
    c = AS.check_theta_square_map(); assert c["Q8_W11_intertwines"] and c["Q8_W13_intertwines"] and not c["D8_W11_intertwines"]
    D = AS.al_lift_on_S0(); assert np.allclose(D["A2"], I) and np.allclose(D["commutator"], -I)          # both lifts keep the projective commutator
    # group generated by the compatible lift: order 8 with six elements of order 4 (Q8), versus two for D8
    def closure(gens):
        seen = [np.eye(2, dtype=complex)]; frontier = list(seen)
        while frontier:
            nxt = []
            for g in frontier:
                for h in gens:
                    k = g @ h
                    if not any(np.allclose(k, s) for s in seen): seen.append(k); nxt.append(k)
            frontier = nxt
        return seen
    def n_order4(G): return sum(np.allclose(np.linalg.matrix_power(g, 4), np.eye(2)) and not np.allclose(np.linalg.matrix_power(g, 2), np.eye(2)) for g in G)
    GQ = closure([Q["A"], Q["B"]]); GD = closure([D["A"].astype(complex), D["B"].astype(complex)])
    assert len(GQ) == 8 and n_order4(GQ) == 6 and len(GD) == 8 and n_order4(GD) == 2
